language: R
warnings_are_errors: true
cache: packages
sudo: true
dist: trusty

r:
  - release

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"
  - Rscript -e "devtools::install_github('jimhester/covr')"
  
env:
  - NOT_CRAN=true
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  
after_success:
  - Rscript -e 'covr::codecov()'

